### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by slava-dzyba** [luckyframework/web#162]
First of all wanted to thank you for the new framework. Looks great and promising.
I didn't notice any mention of websockets functionality in the framework.
Is there any plans for implementing websockets support? Can't wait to see something as powerful as Phoenix's channels.

**Comment by 5minpause** [comment]
Hi @slava-dzyba. I am not a maintainer of this project, but I did notice this first milestone that they are trying to reach: https://github.com/luckyframework/web/milestone/2
> Things like websockets are nice, but won't be included as part of this since most of the apps we build don't need it.

So I'd say websockets will probably be built at some point but I guess there's no clear roadmap for that yet. But @paulcsmith will probably clear that up for you ;)

**Comment by paulcsmith** [comment]
@slava-dzyba, @5minpause pretty much nailed it. Websockets will *definitely* be added, but it will be after a few other things are done.

The main priorities are found on the milestone @5minpause  linked to. They are the things that most projects need. There are also a number of things I want to add to LuckyRecord that will make querying and saving a lot nicer. Once that's done web socket support will be added :D

Thanks for asking!

**Comment by fohara** [comment]
I see that [Milestone 2](https://github.com/luckyframework/lucky/milestone/2) has been completed, and that [Milestone 3](https://github.com/luckyframework/lucky/milestone/3) is in progress, but it also doesn't mention WebSocket support.

Is there a general roadmap for when it (and other Lucky features) might be scheduled for development? Very exciting framework btw!

**Comment by paulcsmith** [comment]
@fohara Thanks for the kind words! I want to make a general Roadmap that is not quite as fine-grained as milestones, but I haven't quite gotten to it (obviously) :)

Here's roughly what it looks like though:

## V1 - Make it so you can do just about everything you need to, and document it

* Improved type safety
  * For route params
  * Typed primary keys in models
* Support for nested forms and arrays of params (for example, creating multiple to-dos at once)
* API docs for all public methods
* Improved error messages in macros
* A guide that goes through building a sample app
* Encrypted secrets
* Class components (instead of modules)
* Document and improve custom SQL queries
* Add support for custom tags (so you can use Vue, Angular, custom components, etc.)

## Next version (likely a minor release like 1.2 or 1.3

* Add type-safe websocket support
* More powerful querying with `or`, subqueries, etc.
* Other things I haven't thought of yet :)

This is super bare-bones and a bit vague, but I hope it clears things up a bit. Websockets can be done with the libs in Crystal. I do want to improve it but it will require a lot of thought to get it type-safe like the rest of Lucky. I don't want to be passing a bunch of strings and untyped JSON around if possible.
