### ISSUE TITLE
Additional installation instructions

### ISSUE THREAD

**Issue by CorbanR** [luckyframework/web#167]
In order to actually get `lucky dev` working I needed to 

1. `brew install heroku`
2. `brew install yarn`
3. `npm install -g brunch1
4. `brunch install` from directory root

And since i'm on sierra `export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` in order for crystal to find the openssl libs. 

Would it make sense to add `heroku`, and `yarn` as deps to the brew formula? Or add some additional installation instructions? I would be happy to submit a pull request, but wanted to check before I did.

**Comment by paulcsmith** [comment]
@CorbanR Thanks for the heads up. There is a guide at https://github.com/luckyframework/website/blob/master/source/guides/installing.html.md.erb that explains the required dependencies for `lucky dev`, it just hasn't been linked to yet because the other guides aren't finished.

If you have a moment I'd *love* it if you could add a note to the macOS section about add the export if you're on High Sierra. There's an issue you can take a look at for suggestions: https://github.com/luckyframework/website/issues/12#issuecomment-340036460

I think for the other stuff like Heroku and yarn, I'd rather let the user decide how to install it. My reasoning there is that sometimes people install node/yarn with nvm or some other package manager and I don't want to mess up their installs by including it in Lucky's brew dependencies. I think once I link to the installation guide this should be ok.

In the future what I'd like to do is throw a helpful error with a message that lets the user know what they need. So if you run `lucky dev` without yarn it'll say "Yarn is required. See {link to instructions} to install it"

As for the brunch thing, I don't think you need to install brunch globally. If you `yarn install` it *should* install brunch locally and use `yarn run brunch` to use the project local version of brunch. Can you try uninstalling brunch globally and making sure it's installed with `yarn install` and see if `lucky dev` works?

Thanks for reporting this!

**Comment by paulcsmith** [comment]
I'm going to close this for this repo and we can continue discussion on the website repo's issue: https://github.com/luckyframework/website/issues/12

**Comment by CorbanR** [comment]
Confirmed, `yarn install` worked. No need to install `brunch` globally.
