### ISSUE TITLE
Outputting HTML in specs

### ISSUE THREAD

**Issue by azbshiri** [luckyframework/web#216]
Outputting HTML in specs could be really helpful to see why the assertion is failed and what's the difference at a glance. So there are questions to answer.

- Where should we put the hook?
- What output should look like?
- What library could we use?

@paulcsmith #94

**Comment by azbshiri** [comment]
Please add more detail @paulcsmith

**Comment by paulcsmith** [comment]
@azbshiri Unfortunately I don't have any details yet because I haven't thought through the other spec helpers enough. I'll add more details here though once I've started on some more proof of concepts for spec helpers. 

For now I'm prioritizing the stuff in these milestones:

* https://github.com/luckyframework/web/milestone/2
* https://github.com/luckyframework/record/milestone/1
* https://github.com/luckyframework/migrator/labels/help%20wanted

Those are some of the things that I think will be necessary for Lucky to be useful for most apps :D

**Comment by paulcsmith** [comment]
Closing this for now, but will reopen when it's easy to be worked on. Just doing this to keep the issues list a bit cleaner.
