### ISSUE TITLE
Env variable error when running migration

### ISSUE THREAD

**Issue by Xosmond** [luckyframework/web#233]
This is the basic example for server configuration:

```crystal
LuckyWeb::Server.configure do
  settings.secret_key_base = "yz+2IwqD68FD5chOKzijDtf8DNFJi3k666Xjr3Fjdxs"
end
```

And I changed it for:
```crystal
LuckyWeb::Server.configure do
  settings.secret_key_base = ENV.fetch("SERVER_SECRET")
end
```

But I try to run a migration `lucky gen.migration CreateUsers`, I got:
```
Missing ENV key: "SERVER_SECRET" (KeyError)
0x1018b1c35: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1018b1bd1: *CallStack#initialize:Array(Pointer(Void)) at ??
0x1018b1ba8: *CallStack::new:CallStack at ??
0x1018ab6e5: *raise<KeyError>:NoReturn at ??
0x1019b4a07: *ENV::fetch<String>:String at ??
0x1018907eb: __crystal_main at ??
0x1018a6868: main at ??
```

This is because lucky is not loading .env file like when I run `lucky dev`, I don't know exactly where is the code to load the .env file. If you can help, will be great.

**Comment by paulcsmith** [comment]
I would take the approach here: https://github.com/luckyframework/cli/commit/ef4c84bf2bc9964c3aaaae93004bbc2ae763c871

It’s ok, and often easier to commit dev only secrets like this, and then use the ENV key in production only. 

Let me know if this works for you!

**Comment by Xosmond** [comment]
Oh i understand now, we should update` lucky cli`, a lot of things are changing.

**Comment by paulcsmith** [comment]
Yeah Lucky has been moving really fast! Hoping to get a new release out soon but just need to finish a few more things first :)

**Comment by tristil** [comment]
@paulcsmith Any reason to not just use something like this? https://github.com/gdotdesign/cr-dotenv I just spent a while being confused by this, since the documentation at https://luckyframework.org/guides/configuration/ makes it seem like it Just Works, but then later the Heroku setup instructions (which has you use `lucky gen.secret_key`) fails if you've set configuration like this. I'm just calling `Dotenv.load` before the configs are required and both paths (server and lucky) now work. BTW really enjoying this framework.

**Comment by paulcsmith** [comment]
@tristil Yes, this behavior is confusing. I think adding the dotenv shard makes a lot of sense! 
https://github.com/luckyframework/lucky_cli/pull/319

**Comment by paulcsmith** [comment]
And I am glad you are enjoying the framework :D
